---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28950.
--- DateTime: 2025/4/4 22:36
---

---比较线程标识与锁的标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    ---释放锁
    return redis.call('del', KEYS[1])
end
return 0